# Generated by Django 5.2.6 on 2025-09-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('is_fork', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('language_count', models.IntegerField()),
                ('topic_count', models.IntegerField()),
                ('disk_usage_kb', models.BigIntegerField()),
                ('pull_requests', models.IntegerField()),
                ('issues', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('default_branch_commit_count', models.FloatField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('assignable_user_count', models.IntegerField()),
                ('code_of_conduct', models.CharField(blank=True, max_length=255, null=True)),
                ('forking_allowed', models.BooleanField()),
                ('name_with_owner', models.CharField(max_length=255, unique=True)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.repository')),
            ],
            options={
                'unique_together': {('repository', 'language')},
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='languages',
            field=models.ManyToManyField(related_name='repositories', through='repos.RepositoryLanguage', to='language.language'),
        ),
    ]
